application: gcl-12
version: 0
runtime: go
api_version: go1
threadsafe: true

handlers:
 - url: /css
   static_dir: www/css

 - url: /img
   static_dir: www/img

 - url: /js
   static_dir: www/js

 - url: /favicon.ico
   static_files: www/img/favicon.ico
   upload: www/img/favicon.ico

 - url: /_ah/spi/.*
   script: _go_app

 - url: /_ah/api/.*
   script: _go_app

 - url: /bin/.*
   script: _go_app

 - url: /
   static_files: www/index.html
   upload: www/index.html
   #secure: always
   #login: admin
   #http_headers:
   # Access-Control-Allow-Origin: https://accounts.google.com

inbound_services:
 - warmup
 #- mail
