/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-05-02 at 00:44:16 UTC 
 * Modify at your own risk.
 */

package com.appspot.gcl_11.service.model;

/**
 * Model definition for ResponseOauth.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the service. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ResponseOauth extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private RequestToken requestToken;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String url;

  /**
   * @return value or {@code null} for none
   */
  public RequestToken getRequestToken() {
    return requestToken;
  }

  /**
   * @param requestToken requestToken or {@code null} for none
   */
  public ResponseOauth setRequestToken(RequestToken requestToken) {
    this.requestToken = requestToken;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUrl() {
    return url;
  }

  /**
   * @param url url or {@code null} for none
   */
  public ResponseOauth setUrl(java.lang.String url) {
    this.url = url;
    return this;
  }

  @Override
  public ResponseOauth set(String fieldName, Object value) {
    return (ResponseOauth) super.set(fieldName, value);
  }

  @Override
  public ResponseOauth clone() {
    return (ResponseOauth) super.clone();
  }

}
