/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-04-26 at 20:35:14 UTC 
 * Modify at your own risk.
 */

package com.appspot.gcl_11.rest.model;

/**
 * Model definition for InappPurchase.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the rest. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class InappPurchase extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long consumptionState;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String developerPayload;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String kind;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long purchaseState;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long purchaseTime;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getConsumptionState() {
    return consumptionState;
  }

  /**
   * @param consumptionState consumptionState or {@code null} for none
   */
  public InappPurchase setConsumptionState(java.lang.Long consumptionState) {
    this.consumptionState = consumptionState;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDeveloperPayload() {
    return developerPayload;
  }

  /**
   * @param developerPayload developerPayload or {@code null} for none
   */
  public InappPurchase setDeveloperPayload(java.lang.String developerPayload) {
    this.developerPayload = developerPayload;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getKind() {
    return kind;
  }

  /**
   * @param kind kind or {@code null} for none
   */
  public InappPurchase setKind(java.lang.String kind) {
    this.kind = kind;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getPurchaseState() {
    return purchaseState;
  }

  /**
   * @param purchaseState purchaseState or {@code null} for none
   */
  public InappPurchase setPurchaseState(java.lang.Long purchaseState) {
    this.purchaseState = purchaseState;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getPurchaseTime() {
    return purchaseTime;
  }

  /**
   * @param purchaseTime purchaseTime or {@code null} for none
   */
  public InappPurchase setPurchaseTime(java.lang.Long purchaseTime) {
    this.purchaseTime = purchaseTime;
    return this;
  }

  @Override
  public InappPurchase set(String fieldName, Object value) {
    return (InappPurchase) super.set(fieldName, value);
  }

  @Override
  public InappPurchase clone() {
    return (InappPurchase) super.clone();
  }

}
