/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-04-26 at 20:35:14 UTC 
 * Modify at your own risk.
 */

package com.appspot.gcl_11.rest.model;

/**
 * Model definition for RequestToken.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the rest. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class RequestToken extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("Secret")
  private java.lang.String secret;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("Token")
  private java.lang.String token;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSecret() {
    return secret;
  }

  /**
   * @param secret secret or {@code null} for none
   */
  public RequestToken setSecret(java.lang.String secret) {
    this.secret = secret;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getToken() {
    return token;
  }

  /**
   * @param token token or {@code null} for none
   */
  public RequestToken setToken(java.lang.String token) {
    this.token = token;
    return this;
  }

  @Override
  public RequestToken set(String fieldName, Object value) {
    return (RequestToken) super.set(fieldName, value);
  }

  @Override
  public RequestToken clone() {
    return (RequestToken) super.clone();
  }

}
