application: gcl-11
version: v0
runtime: go
api_version: go1
threadsafe: true

handlers:

 - url: /_ah/spi/.*
   script: _go_app

 - url: /css
   static_dir: www/css

 - url: /img
   static_dir: www/img

 - url: /js
   static_dir: www/js

 - url: /favicon.ico
   static_files: www/img/favicon.ico
   upload: www/img/favicon.ico

 - url: /
   static_files: www/index.html
   upload: www/index.html
   #secure: always
   #login: admin
   #http_headers:
   # Access-Control-Allow-Origin: https://accounts.google.com

inbound_services:
 - warmup
 #- mail

#skip_files:
# - ^(.*/)?\.git$
# - ^(.*/)?\.idea$

#- url: /(.*\.html)
#  static_files: www/\1
#  upload: www/(.*\.html)
