application: gcl-11
version: v1
runtime: go
api_version: go1
threadsafe: true

handlers:
 - url: /_ah/spi/.*
   script: _go_app

 - url: /_ah/api/.*
   script: _go_app

 - url: /bin/*
   script: _go_app

 - url: /css
   static_dir: www/css

 - url: /img
   static_dir: www/img

 - url: /js
   static_dir: www/js

 - url: /fonts/(.*\.woff)
   static_files: www/fonts/\1
   upload: www/fonts/(.*\.woff)
   mime_type: font/woff

 - url: /fonts/(.*\.svg)
   static_files: www/fonts/\1
   upload: www/fonts/(.*\.svg)
   mime_type: image/svg+xml

 - url: /fonts/(.*\.eot)
   static_files: www/fonts/\1
   upload: www/fonts/(.*\.eot)
   mime_type: application/vnd.ms-fontobject

 - url: /fonts/(.*\.ttf)
   static_files: www/fonts/\1
   upload: www/fonts/(.*\.ttf)
   mime_type: application/x-font-ttf

 - url: /fonts/(.*\.otf)
   static_files: www/fonts/\1
   upload: www/fonts/(.*\.otf)
   mime_type: application/x-font-otf

 - url: /(.*\.html)
   static_files: www/\1
   upload: www/(.*\.html)

 - url: /
   static_files: www/index.html
   upload: www/index.html
   secure: always

 - url: /favicon.ico
   static_files: www/img/favicon.ico
   upload: www/img/favicon.ico

inbound_services:
 - warmup

#skip_files:
# - ^(.*/)?\.git$
# - ^(.*/)?\.idea$

#http_headers:
# Access-Control-Allow-Origin: https://gcl-12.appspot.com

#login: admin

#http_headers:
# Content-Type: image/x-icon

