/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-04-26 at 20:35:14 UTC 
 * Modify at your own risk.
 */

package com.appspot.gcl_11.rest;

/**
 * Service definition for Rest (v0).
 *
 * <p>
 * API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link RestRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Rest extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the rest library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://gcl-11.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "rest/v0/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Rest(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Rest(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the Facebook collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Rest rest = new Rest(...);}
   *   {@code Rest.Facebook.List request = rest.facebook().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Facebook facebook() {
    return new Facebook();
  }

  /**
   * The "facebook" collection of methods.
   */
  public class Facebook {

    /**
     * Oauth callback.
     *
     * Create a request for the method "facebook.callback".
     *
     * This request holds the parameters needed by the rest server.  After setting any optional
     * parameters, call the {@link Callback#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.gcl_11.rest.model.Token}
     * @return the request
     */
    public Callback callback(com.appspot.gcl_11.rest.model.Token content) throws java.io.IOException {
      Callback result = new Callback(content);
      initialize(result);
      return result;
    }

    public class Callback extends RestRequest<com.appspot.gcl_11.rest.model.Token> {

      private static final String REST_PATH = "facebook/callback";

      /**
       * Oauth callback.
       *
       * Create a request for the method "facebook.callback".
       *
       * This request holds the parameters needed by the the rest server.  After setting any optional
       * parameters, call the {@link Callback#execute()} method to invoke the remote operation. <p>
       * {@link
       * Callback#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.gcl_11.rest.model.Token}
       * @since 1.13
       */
      protected Callback(com.appspot.gcl_11.rest.model.Token content) {
        super(Rest.this, "POST", REST_PATH, content, com.appspot.gcl_11.rest.model.Token.class);
      }

      @Override
      public Callback setAlt(java.lang.String alt) {
        return (Callback) super.setAlt(alt);
      }

      @Override
      public Callback setFields(java.lang.String fields) {
        return (Callback) super.setFields(fields);
      }

      @Override
      public Callback setKey(java.lang.String key) {
        return (Callback) super.setKey(key);
      }

      @Override
      public Callback setOauthToken(java.lang.String oauthToken) {
        return (Callback) super.setOauthToken(oauthToken);
      }

      @Override
      public Callback setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Callback) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Callback setQuotaUser(java.lang.String quotaUser) {
        return (Callback) super.setQuotaUser(quotaUser);
      }

      @Override
      public Callback setUserIp(java.lang.String userIp) {
        return (Callback) super.setUserIp(userIp);
      }

      @Override
      public Callback set(String parameterName, Object value) {
        return (Callback) super.set(parameterName, value);
      }
    }

  }

  /**
   * An accessor for creating requests from the Google collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Rest rest = new Rest(...);}
   *   {@code Rest.Google.List request = rest.google().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Google google() {
    return new Google();
  }

  /**
   * The "google" collection of methods.
   */
  public class Google {

    /**
     * Oauth callback.
     *
     * Create a request for the method "google.callback".
     *
     * This request holds the parameters needed by the rest server.  After setting any optional
     * parameters, call the {@link Callback#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.gcl_11.rest.model.Message}
     * @return the request
     */
    public Callback callback(com.appspot.gcl_11.rest.model.Message content) throws java.io.IOException {
      Callback result = new Callback(content);
      initialize(result);
      return result;
    }

    public class Callback extends RestRequest<com.appspot.gcl_11.rest.model.Message> {

      private static final String REST_PATH = "google/callback";

      /**
       * Oauth callback.
       *
       * Create a request for the method "google.callback".
       *
       * This request holds the parameters needed by the the rest server.  After setting any optional
       * parameters, call the {@link Callback#execute()} method to invoke the remote operation. <p>
       * {@link
       * Callback#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.gcl_11.rest.model.Message}
       * @since 1.13
       */
      protected Callback(com.appspot.gcl_11.rest.model.Message content) {
        super(Rest.this, "POST", REST_PATH, content, com.appspot.gcl_11.rest.model.Message.class);
      }

      @Override
      public Callback setAlt(java.lang.String alt) {
        return (Callback) super.setAlt(alt);
      }

      @Override
      public Callback setFields(java.lang.String fields) {
        return (Callback) super.setFields(fields);
      }

      @Override
      public Callback setKey(java.lang.String key) {
        return (Callback) super.setKey(key);
      }

      @Override
      public Callback setOauthToken(java.lang.String oauthToken) {
        return (Callback) super.setOauthToken(oauthToken);
      }

      @Override
      public Callback setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Callback) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Callback setQuotaUser(java.lang.String quotaUser) {
        return (Callback) super.setQuotaUser(quotaUser);
      }

      @Override
      public Callback setUserIp(java.lang.String userIp) {
        return (Callback) super.setUserIp(userIp);
      }

      @Override
      public Callback set(String parameterName, Object value) {
        return (Callback) super.set(parameterName, value);
      }
    }
    /**
     * Oauth2 google purchases.
     *
     * Create a request for the method "google.purchases".
     *
     * This request holds the parameters needed by the rest server.  After setting any optional
     * parameters, call the {@link Purchases#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.gcl_11.rest.model.Iab}
     * @return the request
     */
    public Purchases purchases(com.appspot.gcl_11.rest.model.Iab content) throws java.io.IOException {
      Purchases result = new Purchases(content);
      initialize(result);
      return result;
    }

    public class Purchases extends RestRequest<com.appspot.gcl_11.rest.model.InappPurchase> {

      private static final String REST_PATH = "google/purchases";

      /**
       * Oauth2 google purchases.
       *
       * Create a request for the method "google.purchases".
       *
       * This request holds the parameters needed by the the rest server.  After setting any optional
       * parameters, call the {@link Purchases#execute()} method to invoke the remote operation. <p>
       * {@link
       * Purchases#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.gcl_11.rest.model.Iab}
       * @since 1.13
       */
      protected Purchases(com.appspot.gcl_11.rest.model.Iab content) {
        super(Rest.this, "POST", REST_PATH, content, com.appspot.gcl_11.rest.model.InappPurchase.class);
      }

      @Override
      public Purchases setAlt(java.lang.String alt) {
        return (Purchases) super.setAlt(alt);
      }

      @Override
      public Purchases setFields(java.lang.String fields) {
        return (Purchases) super.setFields(fields);
      }

      @Override
      public Purchases setKey(java.lang.String key) {
        return (Purchases) super.setKey(key);
      }

      @Override
      public Purchases setOauthToken(java.lang.String oauthToken) {
        return (Purchases) super.setOauthToken(oauthToken);
      }

      @Override
      public Purchases setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Purchases) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Purchases setQuotaUser(java.lang.String quotaUser) {
        return (Purchases) super.setQuotaUser(quotaUser);
      }

      @Override
      public Purchases setUserIp(java.lang.String userIp) {
        return (Purchases) super.setUserIp(userIp);
      }

      @Override
      public Purchases set(String parameterName, Object value) {
        return (Purchases) super.set(parameterName, value);
      }
    }
    /**
     * Oauth revoke.
     *
     * Create a request for the method "google.revoke".
     *
     * This request holds the parameters needed by the rest server.  After setting any optional
     * parameters, call the {@link Revoke#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.gcl_11.rest.model.Message}
     * @return the request
     */
    public Revoke revoke(com.appspot.gcl_11.rest.model.Message content) throws java.io.IOException {
      Revoke result = new Revoke(content);
      initialize(result);
      return result;
    }

    public class Revoke extends RestRequest<com.appspot.gcl_11.rest.model.Message> {

      private static final String REST_PATH = "google/revoke";

      /**
       * Oauth revoke.
       *
       * Create a request for the method "google.revoke".
       *
       * This request holds the parameters needed by the the rest server.  After setting any optional
       * parameters, call the {@link Revoke#execute()} method to invoke the remote operation. <p> {@link
       * Revoke#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.gcl_11.rest.model.Message}
       * @since 1.13
       */
      protected Revoke(com.appspot.gcl_11.rest.model.Message content) {
        super(Rest.this, "POST", REST_PATH, content, com.appspot.gcl_11.rest.model.Message.class);
      }

      @Override
      public Revoke setAlt(java.lang.String alt) {
        return (Revoke) super.setAlt(alt);
      }

      @Override
      public Revoke setFields(java.lang.String fields) {
        return (Revoke) super.setFields(fields);
      }

      @Override
      public Revoke setKey(java.lang.String key) {
        return (Revoke) super.setKey(key);
      }

      @Override
      public Revoke setOauthToken(java.lang.String oauthToken) {
        return (Revoke) super.setOauthToken(oauthToken);
      }

      @Override
      public Revoke setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Revoke) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Revoke setQuotaUser(java.lang.String quotaUser) {
        return (Revoke) super.setQuotaUser(quotaUser);
      }

      @Override
      public Revoke setUserIp(java.lang.String userIp) {
        return (Revoke) super.setUserIp(userIp);
      }

      @Override
      public Revoke set(String parameterName, Object value) {
        return (Revoke) super.set(parameterName, value);
      }
    }
    /**
     * Oauth2 google storage.
     *
     * Create a request for the method "google.storage".
     *
     * This request holds the parameters needed by the rest server.  After setting any optional
     * parameters, call the {@link Storage#execute()} method to invoke the remote operation.
     *
     * @return the request
     */
    public Storage storage() throws java.io.IOException {
      Storage result = new Storage();
      initialize(result);
      return result;
    }

    public class Storage extends RestRequest<com.appspot.gcl_11.rest.model.Message> {

      private static final String REST_PATH = "google/storage";

      /**
       * Oauth2 google storage.
       *
       * Create a request for the method "google.storage".
       *
       * This request holds the parameters needed by the the rest server.  After setting any optional
       * parameters, call the {@link Storage#execute()} method to invoke the remote operation. <p>
       * {@link
       * Storage#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected Storage() {
        super(Rest.this, "GET", REST_PATH, null, com.appspot.gcl_11.rest.model.Message.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public Storage setAlt(java.lang.String alt) {
        return (Storage) super.setAlt(alt);
      }

      @Override
      public Storage setFields(java.lang.String fields) {
        return (Storage) super.setFields(fields);
      }

      @Override
      public Storage setKey(java.lang.String key) {
        return (Storage) super.setKey(key);
      }

      @Override
      public Storage setOauthToken(java.lang.String oauthToken) {
        return (Storage) super.setOauthToken(oauthToken);
      }

      @Override
      public Storage setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Storage) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Storage setQuotaUser(java.lang.String quotaUser) {
        return (Storage) super.setQuotaUser(quotaUser);
      }

      @Override
      public Storage setUserIp(java.lang.String userIp) {
        return (Storage) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String product;

      /**

       */
      public java.lang.String getProduct() {
        return product;
      }

      public Storage setProduct(java.lang.String product) {
        this.product = product;
        return this;
      }

      @com.google.api.client.util.Key
      private java.lang.String receipt;

      /**

       */
      public java.lang.String getReceipt() {
        return receipt;
      }

      public Storage setReceipt(java.lang.String receipt) {
        this.receipt = receipt;
        return this;
      }

      @Override
      public Storage set(String parameterName, Object value) {
        return (Storage) super.set(parameterName, value);
      }
    }

  }

  /**
   * An accessor for creating requests from the Greetings collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Rest rest = new Rest(...);}
   *   {@code Rest.Greetings.List request = rest.greetings().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Greetings greetings() {
    return new Greetings();
  }

  /**
   * The "greetings" collection of methods.
   */
  public class Greetings {

    /**
     * Login.
     *
     * Create a request for the method "greetings.authed".
     *
     * This request holds the parameters needed by the rest server.  After setting any optional
     * parameters, call the {@link Authed#execute()} method to invoke the remote operation.
     *
     * @return the request
     */
    public Authed authed() throws java.io.IOException {
      Authed result = new Authed();
      initialize(result);
      return result;
    }

    public class Authed extends RestRequest<com.appspot.gcl_11.rest.model.Response> {

      private static final String REST_PATH = "greetings/authed";

      /**
       * Login.
       *
       * Create a request for the method "greetings.authed".
       *
       * This request holds the parameters needed by the the rest server.  After setting any optional
       * parameters, call the {@link Authed#execute()} method to invoke the remote operation. <p> {@link
       * Authed#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected Authed() {
        super(Rest.this, "POST", REST_PATH, null, com.appspot.gcl_11.rest.model.Response.class);
      }

      @Override
      public Authed setAlt(java.lang.String alt) {
        return (Authed) super.setAlt(alt);
      }

      @Override
      public Authed setFields(java.lang.String fields) {
        return (Authed) super.setFields(fields);
      }

      @Override
      public Authed setKey(java.lang.String key) {
        return (Authed) super.setKey(key);
      }

      @Override
      public Authed setOauthToken(java.lang.String oauthToken) {
        return (Authed) super.setOauthToken(oauthToken);
      }

      @Override
      public Authed setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Authed) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Authed setQuotaUser(java.lang.String quotaUser) {
        return (Authed) super.setQuotaUser(quotaUser);
      }

      @Override
      public Authed setUserIp(java.lang.String userIp) {
        return (Authed) super.setUserIp(userIp);
      }

      @Override
      public Authed set(String parameterName, Object value) {
        return (Authed) super.set(parameterName, value);
      }
    }
    /**
     * Datastore.
     *
     * Create a request for the method "greetings.datastore".
     *
     * This request holds the parameters needed by the rest server.  After setting any optional
     * parameters, call the {@link Datastore#execute()} method to invoke the remote operation.
     *
     * @return the request
     */
    public Datastore datastore() throws java.io.IOException {
      Datastore result = new Datastore();
      initialize(result);
      return result;
    }

    public class Datastore extends RestRequest<com.appspot.gcl_11.rest.model.Response> {

      private static final String REST_PATH = "greetings/datastore";

      /**
       * Datastore.
       *
       * Create a request for the method "greetings.datastore".
       *
       * This request holds the parameters needed by the the rest server.  After setting any optional
       * parameters, call the {@link Datastore#execute()} method to invoke the remote operation. <p>
       * {@link
       * Datastore#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected Datastore() {
        super(Rest.this, "GET", REST_PATH, null, com.appspot.gcl_11.rest.model.Response.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public Datastore setAlt(java.lang.String alt) {
        return (Datastore) super.setAlt(alt);
      }

      @Override
      public Datastore setFields(java.lang.String fields) {
        return (Datastore) super.setFields(fields);
      }

      @Override
      public Datastore setKey(java.lang.String key) {
        return (Datastore) super.setKey(key);
      }

      @Override
      public Datastore setOauthToken(java.lang.String oauthToken) {
        return (Datastore) super.setOauthToken(oauthToken);
      }

      @Override
      public Datastore setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Datastore) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Datastore setQuotaUser(java.lang.String quotaUser) {
        return (Datastore) super.setQuotaUser(quotaUser);
      }

      @Override
      public Datastore setUserIp(java.lang.String userIp) {
        return (Datastore) super.setUserIp(userIp);
      }

      @Override
      public Datastore set(String parameterName, Object value) {
        return (Datastore) super.set(parameterName, value);
      }
    }
    /**
     * Get greeting.
     *
     * Create a request for the method "greetings.getGreeting".
     *
     * This request holds the parameters needed by the rest server.  After setting any optional
     * parameters, call the {@link GetGreeting#execute()} method to invoke the remote operation.
     *
     * @param id [default: 0]
    [minimum: 0]
    [maximum: 1]
     * @return the request
     */
    public GetGreeting getGreeting(java.lang.Integer id) throws java.io.IOException {
      GetGreeting result = new GetGreeting(id);
      initialize(result);
      return result;
    }

    public class GetGreeting extends RestRequest<com.appspot.gcl_11.rest.model.Response> {

      private static final String REST_PATH = "response/{id}";

      /**
       * Get greeting.
       *
       * Create a request for the method "greetings.getGreeting".
       *
       * This request holds the parameters needed by the the rest server.  After setting any optional
       * parameters, call the {@link GetGreeting#execute()} method to invoke the remote operation. <p>
       * {@link
       * GetGreeting#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param id [default: 0]
    [minimum: 0]
    [maximum: 1]
       * @since 1.13
       */
      protected GetGreeting(java.lang.Integer id) {
        super(Rest.this, "GET", REST_PATH, null, com.appspot.gcl_11.rest.model.Response.class);
        this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public GetGreeting setAlt(java.lang.String alt) {
        return (GetGreeting) super.setAlt(alt);
      }

      @Override
      public GetGreeting setFields(java.lang.String fields) {
        return (GetGreeting) super.setFields(fields);
      }

      @Override
      public GetGreeting setKey(java.lang.String key) {
        return (GetGreeting) super.setKey(key);
      }

      @Override
      public GetGreeting setOauthToken(java.lang.String oauthToken) {
        return (GetGreeting) super.setOauthToken(oauthToken);
      }

      @Override
      public GetGreeting setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetGreeting) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetGreeting setQuotaUser(java.lang.String quotaUser) {
        return (GetGreeting) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetGreeting setUserIp(java.lang.String userIp) {
        return (GetGreeting) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Integer id;

      /**
     [ default: 0] minimum: 0] maximum: 1]
       */
      public java.lang.Integer getId() {
        return id;
      }

      public GetGreeting setId(java.lang.Integer id) {
        this.id = id;
        return this;
      }

      @Override
      public GetGreeting set(String parameterName, Object value) {
        return (GetGreeting) super.set(parameterName, value);
      }
    }
    /**
     * List of greetings.
     *
     * Create a request for the method "greetings.listGreeting".
     *
     * This request holds the parameters needed by the rest server.  After setting any optional
     * parameters, call the {@link ListGreeting#execute()} method to invoke the remote operation.
     *
     * @return the request
     */
    public ListGreeting listGreeting() throws java.io.IOException {
      ListGreeting result = new ListGreeting();
      initialize(result);
      return result;
    }

    public class ListGreeting extends RestRequest<com.appspot.gcl_11.rest.model.ResponseList> {

      private static final String REST_PATH = "response";

      /**
       * List of greetings.
       *
       * Create a request for the method "greetings.listGreeting".
       *
       * This request holds the parameters needed by the the rest server.  After setting any optional
       * parameters, call the {@link ListGreeting#execute()} method to invoke the remote operation. <p>
       * {@link
       * ListGreeting#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected ListGreeting() {
        super(Rest.this, "GET", REST_PATH, null, com.appspot.gcl_11.rest.model.ResponseList.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public ListGreeting setAlt(java.lang.String alt) {
        return (ListGreeting) super.setAlt(alt);
      }

      @Override
      public ListGreeting setFields(java.lang.String fields) {
        return (ListGreeting) super.setFields(fields);
      }

      @Override
      public ListGreeting setKey(java.lang.String key) {
        return (ListGreeting) super.setKey(key);
      }

      @Override
      public ListGreeting setOauthToken(java.lang.String oauthToken) {
        return (ListGreeting) super.setOauthToken(oauthToken);
      }

      @Override
      public ListGreeting setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (ListGreeting) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public ListGreeting setQuotaUser(java.lang.String quotaUser) {
        return (ListGreeting) super.setQuotaUser(quotaUser);
      }

      @Override
      public ListGreeting setUserIp(java.lang.String userIp) {
        return (ListGreeting) super.setUserIp(userIp);
      }

      @Override
      public ListGreeting set(String parameterName, Object value) {
        return (ListGreeting) super.set(parameterName, value);
      }
    }
    /**
     * Multiply greeting.
     *
     * Create a request for the method "greetings.multiply".
     *
     * This request holds the parameters needed by the rest server.  After setting any optional
     * parameters, call the {@link Multiply#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.gcl_11.rest.model.Multiply}
     * @return the request
     */
    public Multiply multiply(com.appspot.gcl_11.rest.model.Multiply content) throws java.io.IOException {
      Multiply result = new Multiply(content);
      initialize(result);
      return result;
    }

    public class Multiply extends RestRequest<com.appspot.gcl_11.rest.model.Response> {

      private static final String REST_PATH = "response";

      /**
       * Multiply greeting.
       *
       * Create a request for the method "greetings.multiply".
       *
       * This request holds the parameters needed by the the rest server.  After setting any optional
       * parameters, call the {@link Multiply#execute()} method to invoke the remote operation. <p>
       * {@link
       * Multiply#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.gcl_11.rest.model.Multiply}
       * @since 1.13
       */
      protected Multiply(com.appspot.gcl_11.rest.model.Multiply content) {
        super(Rest.this, "POST", REST_PATH, content, com.appspot.gcl_11.rest.model.Response.class);
      }

      @Override
      public Multiply setAlt(java.lang.String alt) {
        return (Multiply) super.setAlt(alt);
      }

      @Override
      public Multiply setFields(java.lang.String fields) {
        return (Multiply) super.setFields(fields);
      }

      @Override
      public Multiply setKey(java.lang.String key) {
        return (Multiply) super.setKey(key);
      }

      @Override
      public Multiply setOauthToken(java.lang.String oauthToken) {
        return (Multiply) super.setOauthToken(oauthToken);
      }

      @Override
      public Multiply setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Multiply) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Multiply setQuotaUser(java.lang.String quotaUser) {
        return (Multiply) super.setQuotaUser(quotaUser);
      }

      @Override
      public Multiply setUserIp(java.lang.String userIp) {
        return (Multiply) super.setUserIp(userIp);
      }

      @Override
      public Multiply set(String parameterName, Object value) {
        return (Multiply) super.set(parameterName, value);
      }
    }
    /**
     * Soap.
     *
     * Create a request for the method "greetings.soap".
     *
     * This request holds the parameters needed by the rest server.  After setting any optional
     * parameters, call the {@link Soap#execute()} method to invoke the remote operation.
     *
     * @return the request
     */
    public Soap soap() throws java.io.IOException {
      Soap result = new Soap();
      initialize(result);
      return result;
    }

    public class Soap extends RestRequest<com.appspot.gcl_11.rest.model.Response> {

      private static final String REST_PATH = "greetings/soap";

      /**
       * Soap.
       *
       * Create a request for the method "greetings.soap".
       *
       * This request holds the parameters needed by the the rest server.  After setting any optional
       * parameters, call the {@link Soap#execute()} method to invoke the remote operation. <p> {@link
       * Soap#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be
       * called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected Soap() {
        super(Rest.this, "GET", REST_PATH, null, com.appspot.gcl_11.rest.model.Response.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public Soap setAlt(java.lang.String alt) {
        return (Soap) super.setAlt(alt);
      }

      @Override
      public Soap setFields(java.lang.String fields) {
        return (Soap) super.setFields(fields);
      }

      @Override
      public Soap setKey(java.lang.String key) {
        return (Soap) super.setKey(key);
      }

      @Override
      public Soap setOauthToken(java.lang.String oauthToken) {
        return (Soap) super.setOauthToken(oauthToken);
      }

      @Override
      public Soap setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Soap) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Soap setQuotaUser(java.lang.String quotaUser) {
        return (Soap) super.setQuotaUser(quotaUser);
      }

      @Override
      public Soap setUserIp(java.lang.String userIp) {
        return (Soap) super.setUserIp(userIp);
      }

      @Override
      public Soap set(String parameterName, Object value) {
        return (Soap) super.set(parameterName, value);
      }
    }

  }

  /**
   * Create a request for the method "googleget".
   *
   * This request holds the parameters needed by the rest server.  After setting any optional
   * parameters, call the {@link Googleget#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public Googleget googleget() throws java.io.IOException {
    Googleget result = new Googleget();
    initialize(result);
    return result;
  }

  public class Googleget extends RestRequest<Void> {

    private static final String REST_PATH = "googleget";

    /**
     * Create a request for the method "googleget".
     *
     * This request holds the parameters needed by the the rest server.  After setting any optional
     * parameters, call the {@link Googleget#execute()} method to invoke the remote operation. <p>
     * {@link
     * Googleget#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected Googleget() {
      super(Rest.this, "GET", REST_PATH, null, Void.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public Googleget setAlt(java.lang.String alt) {
      return (Googleget) super.setAlt(alt);
    }

    @Override
    public Googleget setFields(java.lang.String fields) {
      return (Googleget) super.setFields(fields);
    }

    @Override
    public Googleget setKey(java.lang.String key) {
      return (Googleget) super.setKey(key);
    }

    @Override
    public Googleget setOauthToken(java.lang.String oauthToken) {
      return (Googleget) super.setOauthToken(oauthToken);
    }

    @Override
    public Googleget setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Googleget) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Googleget setQuotaUser(java.lang.String quotaUser) {
      return (Googleget) super.setQuotaUser(quotaUser);
    }

    @Override
    public Googleget setUserIp(java.lang.String userIp) {
      return (Googleget) super.setUserIp(userIp);
    }

    @Override
    public Googleget set(String parameterName, Object value) {
      return (Googleget) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "googleput".
   *
   * This request holds the parameters needed by the rest server.  After setting any optional
   * parameters, call the {@link Googleput#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public Googleput googleput() throws java.io.IOException {
    Googleput result = new Googleput();
    initialize(result);
    return result;
  }

  public class Googleput extends RestRequest<Void> {

    private static final String REST_PATH = "googleput";

    /**
     * Create a request for the method "googleput".
     *
     * This request holds the parameters needed by the the rest server.  After setting any optional
     * parameters, call the {@link Googleput#execute()} method to invoke the remote operation. <p>
     * {@link
     * Googleput#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected Googleput() {
      super(Rest.this, "GET", REST_PATH, null, Void.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public Googleput setAlt(java.lang.String alt) {
      return (Googleput) super.setAlt(alt);
    }

    @Override
    public Googleput setFields(java.lang.String fields) {
      return (Googleput) super.setFields(fields);
    }

    @Override
    public Googleput setKey(java.lang.String key) {
      return (Googleput) super.setKey(key);
    }

    @Override
    public Googleput setOauthToken(java.lang.String oauthToken) {
      return (Googleput) super.setOauthToken(oauthToken);
    }

    @Override
    public Googleput setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Googleput) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Googleput setQuotaUser(java.lang.String quotaUser) {
      return (Googleput) super.setQuotaUser(quotaUser);
    }

    @Override
    public Googleput setUserIp(java.lang.String userIp) {
      return (Googleput) super.setUserIp(userIp);
    }

    @Override
    public Googleput set(String parameterName, Object value) {
      return (Googleput) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Rest}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Rest}. */
    @Override
    public Rest build() {
      return new Rest(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link RestRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setRestRequestInitializer(
        RestRequestInitializer restRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(restRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
